
name: flutter_master_template
description: A production-ready Flutter application with comprehensive development standards
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.4

  # Navigation
  go_router: ^12.1.3

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  connectivity_plus: ^5.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Image Handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0

  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  local_auth: ^2.1.7

  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Functional Programming
  dartz: ^0.10.1

  # Others
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  freezed: ^2.4.6

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
